image: golang:latest

stages:
  - build
  - test

services:
  - golang:latest

before_script:
#  - apt-get remove docker docker-engine docker.io containerd runc -y
#  - apt-get update -y
#  - apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#  - apt-key fingerprint 0EBFCD88
#  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update -y
#  - apt-get install docker-ce docker-ce-cli containerd.io -y
  - docker info

build-services-job:
  stage: build
  script:
    - echo "Check the `make` version, then build some Makefile project files:"
    - make -v
    - make build

test-code-job:
  stage: test
  script:
    - make test