// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"gitlab.com/adesso-turkey/loyalty-backend-microservices/internal/util/packer"
	"gitlab.com/adesso-turkey/loyalty-backend-microservices/pkg/config"
	"gitlab.com/adesso-turkey/loyalty-backend-microservices/service/fabric"
)

// Injectors from wire.go:

func InitializeConfig() *config.Config {
	fileReader := config.NewYamlConfig()
	configConfig := config.NewConfig(fileReader)
	return configConfig
}

func InitializeCcPack() packer.FilePacker {
	archiver := packer.NewArch()
	filePacker := packer.NewCcPack(archiver)
	return filePacker
}

func InitializeExternalCcConfig() *fabric.ExternalCcConfig {
	configConfig := InitializeConfig()
	externalCcConfig := fabric.NewExternalCcConfig(configConfig)
	return externalCcConfig
}
