basePath: /
definitions:
  merchant.CreateDto:
    properties:
      location:
        $ref: '#/definitions/merchant.Location'
      name:
        type: string
    required:
    - location
    - name
    type: object
  merchant.Location:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    required:
    - latitude
    - longitude
    type: object
  merchant.Merchant:
    properties:
      id:
        type: string
      location:
        $ref: '#/definitions/merchant.Location'
      name:
        type: string
    required:
    - location
    - name
    type: object
  merchant.UpdateDto:
    properties:
      location:
        $ref: '#/definitions/merchant.Location'
        description: 'TODO: Location didn''t change'
      name:
        type: string
    required:
    - location
    - name
    type: object
  util.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is the merchant API of LoyaltyDLT project
  title: Merchant API
  version: "1.0"
paths:
  /merchants:
    get:
      description: Get all merchants
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/merchant.Merchant'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Read all merchant data
      tags:
      - merchant
    post:
      consumes:
      - application/json
      description: Create a new merchant
      parameters:
      - description: New Merchant
        in: body
        name: merchant
        required: true
        schema:
          $ref: '#/definitions/merchant.CreateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/merchant.Merchant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Create a merchant
      tags:
      - merchant
  /merchants/{id}:
    delete:
      description: Delete a merchant data
      parameters:
      - description: Merchant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Delete a merchant data
      tags:
      - merchant
    get:
      description: Get a merchant data
      parameters:
      - description: Merchant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/merchant.Merchant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Read a merchant data
      tags:
      - merchant
    put:
      consumes:
      - application/json
      description: Update a merchant data
      parameters:
      - description: Update Merchant
        in: body
        name: merchant
        required: true
        schema:
          $ref: '#/definitions/merchant.UpdateDto'
      - description: Merchant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/merchant.Merchant'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Update a merchant data
      tags:
      - merchant
swagger: "2.0"
