// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/campaigns": {
            "post": {
                "description": "Create a new campaign",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "campaign"
                ],
                "summary": "Create a campaign",
                "parameters": [
                    {
                        "description": "New Campaign",
                        "name": "campaign",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Campaign"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Campaign"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Campaign": {
            "type": "object",
            "required": [
                "components",
                "name",
                "private_key",
                "public_key"
            ],
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Container"
                    }
                },
                "consumer_age": {
                    "type": "string"
                },
                "consumer_freq": {
                    "type": "string"
                },
                "distribution": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "partnered": {
                    "type": "boolean"
                },
                "private_key": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "model.ComponentComponent": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "benefits": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "city": {
                    "type": "string"
                },
                "distributor": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "expiration": {
                    "type": "boolean"
                },
                "items": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "paid": {
                    "type": "boolean"
                },
                "tasks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "tier": {
                    "type": "integer"
                }
            }
        },
        "model.Container": {
            "type": "object",
            "required": [
                "component",
                "component_type",
                "order"
            ],
            "properties": {
                "component": {
                    "description": "Component     json.RawMessage ` + "`" + `json:\"component\" validate:\"required\"` + "`" + `",
                    "$ref": "#/definitions/model.ComponentComponent"
                },
                "component_type": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                }
            }
        },
        "util.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:80",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Campaign API",
	Description: "This is the campaign API of LoyaltyDLT project",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
